# Generated by Django 4.0.4 on 2022-12-06 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0021_csrf_user_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='zodiac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=200)),
                ('count', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
            ],
        ),
    ]
