# Generated by Django 4.0.4 on 2022-12-07 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0022_zodiac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('balance', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
            ],
        ),
    ]
