# Generated by Django 4.0.4 on 2022-12-07 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0023_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalWithdrawn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('total', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
            ],
        ),
    ]
