# Generated by Django 4.0.4 on 2022-12-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0024_totalwithdrawn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalWithdrawn',
            new_name='ATM',
        ),
    ]
