version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network
    depends_on:
      - web
    restart: unless-stopped

  migration:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py populate_challenges"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my_network

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 6 pygoat.wsgi
    container_name: pygoat-web
    ports: []
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
