# Generated by Django 4.0.2 on 2022-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0016_alter_blogs_blog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CF_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO introduction_cf_user (username, password) VALUES "
            "('alex', '9d6edee6ce9312981084bd98eb3751ee'),"
            "('admin', 'c93ccd78b2076528346216b3b2f701e6'),"
            "('rupak', '5ee3547adb4481902349bdd0f2ffba93');"
        ),
    ]
