from django.urls import include, path

from . import mitre, views

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("", views.home, name="homepage"),
    path("xss", views.xss, name="xss"),
    path("sql", views.sql, name="sql"),
    path("insec_des", views.insec_des, name="insec_des"),
    path("xxe", views.xxe, name="xxe"),
    path("auth", views.auth_home, name="auth_home"),
    path("ba", views.ba, name="Broken Access Control"),
    path("data_exp", views.data_exp, name="data_exp"),
    path("robots.txt", views.robots, name="robots.txt"),
    path("500error", views.error, name="500error"),
    path("cmd", views.cmd, name="Command Injection"),
    path("bau", views.bau, name="Broken Authe"),
    path("sec_mis", views.sec_mis, name="Security Misconfiguration"),
    path("a9", views.a9, name="A9"),
    path("a10", views.a10, name="A10"),
    path("insecure-design", views.insec_desgine, name="insecure-design"),
    path("broken_access_control", views.a1_broken_access, name="broken_access"),
    path("path_traversal_lab", views.path_traversal_lab_page, name="path_traversal_lab"),
    path("ssrf", views.ssrf, name="SSRF"),
    path("injection", views.injection, name="injection"),
    path("ssti", views.ssti, name="SSTI"),
    path("cryptographic_failure", views.crypto_failure, name="cryptographic_failure"),
    path("A03", views.supply_chain_failures, name="supply_chain_failures"),
    path("auth_failure", views.auth_failure, name="auth_failure"),
    path("2021/A8", views.software_and_data_integrity_failure, name="A8"),
    ##------------------- mitre endpoints --------------------------------------------------------------|
    path("mitre/1", mitre.mitre_top1, name="mitre_top1"),
    path("mitre/2", mitre.mitre_top2, name="mitre_top2"),
    path("mitre/3", mitre.mitre_top3, name="mitre_top3"),
    path("mitre/4", mitre.mitre_top4, name="mitre_top4"),
    path("mitre/5", mitre.mitre_top5, name="mitre_top5"),
    path("mitre/6", mitre.mitre_top6, name="mitre_top6"),
    path("mitre/7", mitre.mitre_top7, name="mitre_top7"),
    path("mitre/8", mitre.mitre_top8, name="mitre_top8"),
    path("mitre/9", mitre.mitre_top9, name="mitre_top9"),
    path("mitre/10", mitre.mitre_top10, name="mitre_top10"),
    path("mitre/11", mitre.mitre_top11, name="mitre_top11"),
    path("mitre/12", mitre.mitre_top12, name="mitre_top12"),
    path("mitre/13", mitre.mitre_top13, name="mitre_top13"),
    path("mitre/14", mitre.mitre_top14, name="mitre_top14"),
    path("mitre/15", mitre.mitre_top15, name="mitre_top15"),
    path("mitre/16", mitre.mitre_top16, name="mitre_top16"),
    path("mitre/17", mitre.mitre_top17, name="mitre_top17"),
    path("mitre/18", mitre.mitre_top18, name="mitre_top18"),
    path("mitre/19", mitre.mitre_top19, name="mitre_top19"),
    path("mitre/20", mitre.mitre_top20, name="mitre_top20"),
    path("mitre/21", mitre.mitre_top21, name="mitre_top21"),
    path("mitre/22", mitre.mitre_top22, name="mitre_top22"),
    path("mitre/23", mitre.mitre_top23, name="mitre_top23"),
    path("mitre/24", mitre.mitre_top24, name="mitre_top24"),
    path("mitre/25", mitre.mitre_top25, name="mitre_top25"),
]
