# Generated by Django 3.0.6 on 2021-04-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faang',
            name='about',
        ),
        migrations.RemoveField(
            model_name='faang',
            name='ceo',
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('faang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.FAANG')),
            ],
        ),
    ]
