# Generated by Django 3.0.6 on 2021-04-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0003_password_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='password',
        ),
    ]
