# Generated by Django 3.0.6 on 2021-04-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0004_auto_20210415_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='login',
        ),
    ]
