# Generated by Django 4.0.3 on 2022-03-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0010_authlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickit', models.CharField(max_length=40, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.authlogin')),
            ],
        ),
    ]
