# Generated by Django 4.2 on 2026-03-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("introduction", "0022_remove_owasp2017_lab_models"),
        ("introduction", "0022_remove_owasp2021_lab_models"),
    ]

    operations = []
