# Generated by Django 4.2 on 2026-08-18 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="🏆",
                        help_text="Emoji or icon class for display",
                        max_length=50,
                    ),
                ),
                (
                    "required_completions",
                    models.PositiveIntegerField(
                        help_text="Number of completed labs/challenges required"
                    ),
                ),
                (
                    "content_type_filter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Any"),
                            ("challenge", "Challenges only"),
                            ("lab", "Labs only"),
                        ],
                        default="",
                        help_text="Restrict to a specific content type, or leave blank for any",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["required_completions"],
            },
        ),
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "multiplier",
                    models.FloatField(
                        default=1.0,
                        help_text="Score multiplier applied to base points (0.1–10.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering (lower = easier)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LabCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("challenge", "Challenge"), ("lab", "Lab")],
                        max_length=10,
                    ),
                ),
                (
                    "content_id",
                    models.PositiveIntegerField(help_text="PK of the Challenge or Lab"),
                ),
                (
                    "content_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized name for display",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Computed: completed_at - started_at in seconds",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoringSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_points",
                    models.PositiveIntegerField(
                        default=100, help_text="Default base points before multipliers"
                    ),
                ),
                (
                    "time_bonus_max",
                    models.FloatField(
                        default=2.0,
                        help_text="Maximum time bonus multiplier (for fastest solves)",
                    ),
                ),
                (
                    "time_bonus_window_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Solves within this many minutes get max time bonus",
                    ),
                ),
                (
                    "time_penalty_floor",
                    models.FloatField(
                        default=0.5,
                        help_text="Minimum time multiplier (for slowest solves)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scoring Settings",
                "verbose_name_plural": "Scoring Settings",
            },
        ),
        migrations.CreateModel(
            name="LabScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_points", models.PositiveIntegerField()),
                ("difficulty_multiplier", models.FloatField()),
                ("time_multiplier", models.FloatField()),
                ("final_score", models.PositiveIntegerField()),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "completion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="scoring.labcompletion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scoring.achievementmilestone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "milestone")},
            },
        ),
        migrations.AddIndex(
            model_name="labscore",
            index=models.Index(
                fields=["user", "-final_score"], name="scoring_lab_user_id_054bf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labcompletion",
            index=models.Index(
                fields=["user", "content_type"], name="scoring_lab_user_id_10e42d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labcompletion",
            index=models.Index(
                fields=["completed_at"], name="scoring_lab_complet_0bfdcc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labcompletion",
            unique_together={("user", "content_type", "content_id")},
        ),
    ]
