# Generated by Django 4.2 on 2026-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_challenge_docker_image_alter_challenge_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('build_location', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
