# Generated by Django 4.2 on 2026-06-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0004_lab"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="is_custom",
            field=models.BooleanField(default=True),
        ),
    ]
