# Generated by Django 4.2 on 2026-08-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0006_lab_is_custom"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabCategoryMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("owasp_2025", "OWASP TOP 10 2025"),
                            ("owasp_2021", "OWASP TOP 10 2021"),
                            ("owasp_2017", "OWASP TOP 10 2017"),
                            ("challenges", "Challenges"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "overview_url_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Django URL name for an overview page (e.g. supply_chain_failures)",
                        max_length=100,
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_mappings",
                        to="challenge.lab",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "sort_order"],
                "unique_together": {("lab", "category", "subcategory")},
            },
        ),
    ]
