# Generated by Django 4.2

from django.db import migrations

def mark_builtin_labs(apps, schema_editor):
    Lab = apps.get_model('challenge', 'Lab')
    builtin_names = [
        "bopla_lab", "business_logic_lab", "security_headers_lab", "a9_uckv_lab",
        "auth_failure_lab", "broken_access_lab", "broken_auth_lab", "command_injection_lab",
        "crypto_failure_lab", "insec_des_lab", "insecure_design_lab", "insufficient_logging_lab",
        "sde", "sec_misconfig", "sensitive_data_exposure", "software_integrity_lab",
        "sql_injection_lab", "ssrf_lab", "template_injection_lab", "xss_lab",
        "xxe_lab", "dependency_attack_lab", "package_injection_lab", "open_source_library_attack_lab"
    ]
    Lab.objects.filter(name__in=builtin_names).update(is_custom=False)

def unmark_builtin_labs(apps, schema_editor):
    Lab = apps.get_model('challenge', 'Lab')
    builtin_names = [
        "bopla_lab", "business_logic_lab", "security_headers_lab", "a9_uckv_lab",
        "auth_failure_lab", "broken_access_lab", "broken_auth_lab", "command_injection_lab",
        "crypto_failure_lab", "insec_des_lab", "insecure_design_lab", "insufficient_logging_lab",
        "sde", "sec_misconfig", "sensitive_data_exposure", "software_integrity_lab",
        "sql_injection_lab", "ssrf_lab", "template_injection_lab", "xss_lab",
        "xxe_lab", "dependency_attack_lab", "package_injection_lab", "open_source_library_attack_lab"
    ]
    Lab.objects.filter(name__in=builtin_names).update(is_custom=True)

class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_lab_is_custom'),
    ]

    operations = [
        migrations.RunPython(mark_builtin_labs, reverse_code=unmark_builtin_labs),
    ]
