# Generated by Django 4.2 on 2026-08-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
        ("challenge", "0006_lab_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="difficulty",
            field=models.ForeignKey(
                blank=True,
                help_text="Difficulty rating (affects score multiplier)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scoring.difficultylevel",
            ),
        ),
        migrations.AddField(
            model_name="lab",
            name="difficulty",
            field=models.ForeignKey(
                blank=True,
                help_text="Difficulty rating (affects score multiplier)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scoring.difficultylevel",
            ),
        ),
    ]
