name: Container Image Scan

on: [push, pull_request]

jobs:
  trivy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pygoat:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2
        with:
          image-ref: 'pygoat:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'