# Generated by Django 4.2 on 2026-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataexposure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
